### ISSUE TITLE
Does not work on Mac 10.6.7: Python 2.6.1

### ISSUE THREAD

**Issue by John-Durr** [ChicoTeam/PyRunner#3]
Traceback (most recent call last):
  File "pyrunner.py", line 1336, in <module>
    mainMenu()
  File "pyrunner.py", line 1273, in mainMenu
    gameInit()
  File "pyrunner.py", line 775, in gameInit
    effectsGroup = WorkingSingle() #group to store effects in
  File "/Library/Python/2.6/site-packages/pygame/sprite.py", line 552, in **init**
    self.add(_sprites)
  File "pyrunner.py", line 522, in add
    pygame.sprite.Group.add(self,spriteAdd)
  File "/Library/Python/2.6/site-packages/pygame/sprite.py", line 365, in add
    self.add(_sprite)
  File "pyrunner.py", line 522, in add
    pygame.sprite.Group.add(self,spriteAdd)
  File "/Library/Python/2.6/site-packages/pygame/sprite.py", line 365, in add
    self.add(*sprite)

[REMOVED A BUNCH OF REDUNDANT LINES]

  File "pyrunner.py", line 522, in add
    pygame.sprite.Group.add(self,spriteAdd)
  File "/Library/Python/2.6/site-packages/pygame/sprite.py", line 365, in add
    self.add(*sprite)
  File "pyrunner.py", line 516, in add
    if self.sprites():
  File "/Library/Python/2.6/site-packages/pygame/sprite.py", line 314, in sprites
    return list(self.spritedict)
RuntimeError: maximum recursion depth exceeded while calling a Python object
Blag-Ivanovs-MacBook-Pro:Pyrunner Blag$

**Comment by jbttn** [comment]
See my commit: https://github.com/ChicoTeam/PyRunner/commit/82eb76fdec63a899ab5edb742ae9149bc5f27aaf

The problem here had to do with a custom written function by the author of the project ( WorkingSingle() ) which was added to fix some issue with a memory leak in the PyGame code.  I first tried to set the maximum recursion limit with the sys.setrecursionlimit() python call but that just led to a crash... the alternative was to use the call the author was trying to bypass which is what I've added in my commit (for OSX only).  The game seems to crawl whenever an effect is on the screen however so the bug that the author was trying to fix might still be there.

**Comment by jbttn** [comment]
Hmm it's worse than I thought, the longer the game goes on the game realllly starts to crawl.  So my fix is an okay temporary solution, but this is still an issue.  We can either A) Find out why the WorkingSingle() call is having problems on OSX specifically or B) Get rid of any effects (basically anything that has to do with the effectsGroup variable) when the game is run on a mac.

**Comment by russplaysguitar** [comment]
Nice work Josh. Moving forward, obviously choice A would be the best. I'm betting there is a memory leak somewhere. I wonder if the "sprites" are getting cleaned up...?

**Comment by russplaysguitar** [comment]
This might be helpful... http://docs.python.org/library/gc.html

**Comment by jbttn** [comment]
http://groups.google.com/group/pygame-mirror-on-google-groups/browse_thread/thread/941b7faa4fe24677/75f31dc827bbd35e?#75f31dc827bbd35e

I used the same method used in the code attached to that post "pygame_memleak2.py".  The slowdowns are no longer happening in the game on OSX.  Apparently this bug is fixed in the newer releases of pygame but the latest stable release is from 2009.  This fix probably works on Windows / Linux as well, try changing the following lines (around line 777) from this:

```
if platform.system() == 'Darwin':
    effectsGroup = pygame.sprite.Group()
else:
    effectsGroup = WorkingSingle() #group to store effects in
```

to this:

```
effectsGroup = pygame.sprite.Group()
```

and see if it still works well in those platforms.

**Comment by russplaysguitar** [comment]
Yup, tested fine! I changed and committed it. I'm going to close this issue now since it is fixed. Good job Josh.
